apiVersion: v1
kind: ConfigMap

metadata:
  name: taskflow-backend-config
  namespace: taskflow

data:

  PORT: "3000"

  REDIS_HOST: "redis-service"

  REDIS_PORT: "6379"

  APP_VERSION: "1.0.0"

  NODE_ENV: "production"
  
  BACKEND_HOST: "backend-service"
  
  BACKEND_PORT: "3000"